apiVersion: apps/v1
kind : Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      batch: c38
  template:
    metadata:
      name: nginx
      labels:
        batch: c38
    spec:
      containers:
      - name: nginx
        image: nginx