apiVersion: apps/v1
kind : Deployment
metadata:
  name: vote-app
spec:
  replicas: 3
  selector:
    matchLabels:
      batch: c38
  template:
    metadata:
      name: vote-app
      labels:
        batch: c38
    spec:
      containers:
      - name: vote-app
        image: dipesh017/demo:vote